spacerouter-service:
  name: "buddy"

  project: "ca/dev/sr/services"

  image:
    registry: "docker.leyoutech.net/platform/services"

  ingress:
    enabled: true
    dns:
      domain: "dev.leyoutech.net"
      subdomain: "buddy"
    routes:
      grpc:
      - package: "buddy.pb"
        services:
        - "PublicService"

  config:
    values:
    - name: "DOCUMENT_STORE_URL"
      value: "couchbase://couchbase"
    secrets:
    - name: "COUCHBASE_USERNAME"
      from:
        name: "couchbase-auth"
        key: "username"
    - name: "COUCHBASE_PASSWORD"
      from:
        name: "couchbase-auth"
        key: "password"
