spacerouter-service:
  name: "chat"

  project: "ca/dev/sr/services"

  image:
    registry: "docker.leyoutech.net/platform/services"

  ingress:
    enabled: true
    dns:
      domain: "dev.leyoutech.net"
      subdomain: "chat"
    routes:
      grpc:
      - package: "chat.pb"
        services:
        - "ChatService"
