name: chat
proto: api
root: ..
generate:
  go: generated/grpc/go

install:
- package: cmd/chat_svc

images:
- name: chat
  entrypoint:
    package: cmd/chat_svc
  dockerfile: build/package/Dockerfile

deployments:
- release: chat
  chart: deployments/helm/chat